use_frameworks!

target 'Lottie-Example' do
  pod 'lottie-ios-extension', :path => '../'

  target 'lottie-ios_Tests' do
    inherit! :search_paths

    
  end
end

target 'Lottie-Example-MacOS' do
  pod 'lottie-ios-extension', :path => '../'
end
